flowchart LR
    subgraph guest [宿泊者画面一覧]
        %% 全ての入り口をTOPページ（共通メニュー）
        TOPページ --> アクセス案内ページ
        TOPページ --> お問い合わせフォーム
        TOPページ --> 客室紹介ページ
        TOPページ --> 宿泊プラン一覧ページ
        
        
        アクセス案内ページ -->|戻る| TOPページ

        %% お問い合わせフロー
        お問い合わせフォーム -->|送信| お問い合わせ完了画面
        %% 送信時に管理者へメール+宿泊者へ完了メール

        お問い合わせ完了画面 -->|戻る| TOPページ

        %% 予約フロー
        宿泊プラン一覧ページ --> 宿泊プラン詳細ページ
        宿泊プラン詳細ページ --> 空室カレンダーページ
        空室カレンダーページ --> 予約フォーム
        予約フォーム --> 予約内容最終確認画面
        %% 予約完了フロー
        予約内容最終確認画面 -->|確定| 予約完了画面
        %% 確定時に宿泊者へ完了メール+管理者へ受付メール

        %%予約フロー中のキャンセルフロー
        宿泊プラン一覧ページ -->|戻る| TOPページ
        宿泊プラン詳細ページ -->|別プランを見る| 宿泊プラン一覧ページ 
        空室カレンダーページ -->|キャンセル| 宿泊プラン一覧ページ 
        予約フォーム -->|キャンセル| 宿泊プラン一覧ページ 
        予約フォーム -->|カレンダーへ| 空室カレンダーページ 
        予約内容最終確認画面 -->|入力画面へ戻る| 予約フォーム
        
        予約完了画面 -->|TOPページへ| TOPページ
        
        %%「解決したい課題」には、「予約しづらいため、予約のハードルが高く、空室率が高い」とあるので、この部屋に泊まりたい！と思った時宿泊プラン一覧ページに飛べると便利かも

        客室紹介ページ-->|プランを見る|宿泊プラン一覧ページ
  end   

    subgraph header[ヘッダー]
        TOP-->TOPページ
        お問い合わせ-->お問い合わせフォーム
        アクセス案内-->アクセス案内ページ
        客室紹介-->客室紹介ページ
        宿泊プラン一覧-->宿泊プラン一覧ページ
    end
    
    