erDiagram
    teachers ||--o{ main_subjects : "specialized"
    classes }o--|| teachers : "class_id"
    classes }o--|| students : "class_id" 

    teachers {
        int id PK "担任・専科"
        string name "名前"
        string specialized "専科"
        int class_id FK "担当クラス"
    }

     
    classes {
        int id PK 
        string grade "学年"
        string class_name "組"
    }

    students {
        int id PK "在籍番号"
    %% TODO プロトタイプ仕様書にある、year,class,numberが抜けている
        string name "氏名"
        int class_id FK "在籍クラス"
    }

    main_subjects {
        int id PK "科目番号"
        string name "(国語, 数学...)"
    }

    exams {
        int id PK
        string quarter "中間・期末"
        string period "前期・後期"
    }

